# -*- coding: utf-8 -*-
"""AIDL Final Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxqfQdT2T7r4EhpF-MJxf3sj7l4qaOjg
"""

# Uncomment below lines on first run
# !pip install spacy google-cloud-vision

# Unzipping model files
# ! unzip models.zip

# Importing Libraries
import spacy
import os 
import json
from google.cloud import vision
import io

# Setting Environment Variable for Vision API
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/fyp-bot-fkvpth-63ef51dcf510.json"

# Setting variables
modelDir = "models/AIDL_NER_DO-0.30_EP-20_90_PERC_DATA"
fileType = "img"
filename = "sample.jpg"

# Initializing vision API
client = vision.ImageAnnotatorClient()

# Loading the saved Spacy model
nlp = spacy.load(modelDir)

def getOutput(type, data):
  """
  Parameters: type: type of data, either img or txt
  Output: Prints the dictionary
  """
  textToPredict = ""
  if (type == "img"):
    with io.open(data, 'rb') as image_file:
        content = image_file.read()
        image = vision.types.Image(content=content)
        text_response = client.text_detection(image=image)
        texts = [text.description for text in text_response.text_annotations]
        textToPredict = texts[0]
  else:
    f = open(data, "r")
    textToPredict = f.read()
  
  doc = nlp(textToPredict)
  max_amt = 0
  i = 1
  data = {}
  items_list = []
  for ent in doc.ents:
    if (ent.label_ == "Total bill amount"):
      try:
        amt = float(ent.text)
        if amt > max_amt:
          data["Total bill amount"] = amt
      except Exception as e:
        print(e)
    elif (ent.label_ == "Items"):
      try:
        items_list.append(ent.text)
      except Exception as e:
        print(e)
    else:
      if ent.label_ in data.keys():
        data[ent.label_+"-"+str(i)] = ent.text
        i +=1
      else:
        data[ent.label_] = ent.text
  data["Items"]=items_list
  data = dict(sorted(data.items()))
  print(json.dumps(data, indent=2))

# Commented out IPython magic to ensure Python compatibility.
# %time
# Calling the function to get the output
getOutput(fileType, filename)